### ISSUE TITLE
highlighting

### ISSUE THREAD

**Issue by StevenClontz** [drewyoungren/utmost-guides#2]
When logged in as guest at https://books.aimath.org/aata/section-note-on-proofs.html I seem unable to highlight. More information on https://drew.youngren.nyc/utmost-guides/section-utmost-specifics.html#subsection-highlighting might be helpful (e.g. "you can't highlight yet but you will by 2019 October").

**Comment by drewyoungren** [comment]
Works on AC, not AATA as yet.
