### ISSUE TITLE
lecture notes section

### ISSUE THREAD

**Issue by StevenClontz** [drewyoungren/utmost-guides#3]
I'm confused as to the purpose of the lecture notes section as it relates to the UTMOST project. I forget my specific responsibilities to the project (since I teach in spring 2021); am I supposed to provide my lecture notes to the program? If so, a reminder of this would be useful on https://drew.youngren.nyc/utmost-guides/section-use-cases-lecture-notes.html

**Comment by drewyoungren** [comment]
No, this is only meant for faculty who might want to take a new approach to their classroom preparation. It may not be relevant to all.
